#!/usr/bin/env bash

set -e
set -x

./adjacents.native A_gen
./adjacents.native A_nuc
./adjacents.native B_gen
./adjacents.native B_nuc
./adjacents.native C_gen
./adjacents.native C_nuc
./adjacents.native DRB_nuc
./adjacents.native DRB1_gen
./adjacents.native DMA_gen
./adjacents.native DMA_nuc
./adjacents.native DMB_gen
./adjacents.native DMB_nuc
./adjacents.native DOA_gen
./adjacents.native DOA_nuc
./adjacents.native DOB_gen
./adjacents.native DOB_nuc
./adjacents.native DPA1_gen
./adjacents.native DPA1_nuc
./adjacents.native DPB1_gen
./adjacents.native DPB1_nuc
./adjacents.native DPB2_gen
./adjacents.native DPB2_nuc
./adjacents.native DQA1_gen
./adjacents.native DQA1_nuc
./adjacents.native DQB1_gen
./adjacents.native DQB1_nuc
./adjacents.native DRA_gen
./adjacents.native DRA_nuc
./adjacents.native DRB1_gen
./adjacents.native DRB3_gen
./adjacents.native DRB4_gen
./adjacents.native DRB_nuc
./adjacents.native E_gen
./adjacents.native E_nuc
./adjacents.native F_gen
./adjacents.native F_nuc
./adjacents.native G_gen
./adjacents.native G_nuc
./adjacents.native HFE_gen
./adjacents.native HFE_nuc
./adjacents.native H_gen
./adjacents.native H_nuc
./adjacents.native J_gen
./adjacents.native J_nuc
./adjacents.native K_gen
./adjacents.native K_nuc
./adjacents.native L_gen
./adjacents.native L_nuc
./adjacents.native MICA_gen
./adjacents.native MICA_nuc
./adjacents.native MICB_gen
./adjacents.native MICB_nuc
./adjacents.native P_gen
./adjacents.native TAP1_gen
./adjacents.native TAP1_nuc
./adjacents.native TAP2_gen
./adjacents.native TAP2_nuc
./adjacents.native V_gen
./adjacents.native V_nuc
./adjacents.native Y_gen
./adjacents.native Y_nuc
